server:
  port: 8090
spring:
  config:
    import: classpath:myconfig.yml
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
bot:
  name: ${botConfig.name}
  token: ${botConfig.token}
rabbitQueue:
  messages:
    update:
      TEXT: ${rabbitConfig.messages.update.TEXT}
    answer: ${rabbitConfig.messages.answer}