server:
  port: 8091
spring:
  config:
    import: classpath:myconfig.yml
  rabbitmq:
    host: ${rabbitmq.host}
    port: ${rabbitmq.port}
    username: ${rabbitmq.username}
    password: ${rabbitmq.password}
  liquibase:
    enabled: false
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: ${db.url}
    username: ${db.username}
    password: ${db.password}
rabbitQueue:
  messages:
    update:
      TEXT: ${rabbitConfig.messages.update.TEXT}
      PHOTO: ${rabbitConfig.messages.update.PHOTO}
    answer:
      PHOTO: ${rabbitConfig.messages.answer.PHOTO}
      TEXT: ${rabbitConfig.messages.answer.TEXT}
buttonName:
  shelterInformation: Информация о приюте
  mainMenu: Главное меню
  unknownCommand: Неизвестная команда
  petReport: Прислать отчет о питомце
  adoption: Как взять животное из приюта
  volunteer: Позвать волонтера
  shelterAddress: Адрес
  workScheduleShelter: Расписание работы приюта
  drivingDirections: Схема проезда
  safetyMeasuresInShelter: Техника безопасности на территории приюта
  securityData: Данные охраны для оформления пропуска на машину
  contactForCommunication: Оставить контактные данные для связи
  listAnimals: Показать весь список животных
  rulesAnimal: Правила знакомства с животным
  listDocuments: Список документов
  recommendations: Рекомендации
  contactVolunteersByPhoneNumber: По номеру телефона
  contactVolunteersByNickname: По имени пользователя
  endChatWithVolunteer: Завершить чат с волонтером
  endChatWithClient: Завершить чат с клиентом
  startChatWithVolunteer: Начать чат с волонтером
  storyOfShelter: Рассказ о приюте
  sendPhoto: Отправить фото
  sendText: Отправить текст
  initCommand: Изменить приют
  backButton: Назад
  reasonsForRefusalOfAdoption: Причины отказа в усыновлении
  transportation: Транспортировка
  homeImprovementForAdultAnimal: Обустройство дома для взрослого животного
  homeImprovementForPuppy: Обустройство дома для щенка
  tipsFromDogHandler: Советы кинолога
  homeImprovementForAnimalWithDisabilities: Обустройство дома для животного с ограниченными возможностями
  listDogHandlers: список кинологов

