server:
  port: 8091
spring:
  rabbitmq:
    host:
    port:
    username:
    password:
  liquibase:
    change-log: classpath:liquibase/changelog-master.yml
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: validate
  datasource:
    url: jdbc:postgresql://94.158.219.127:5432/toptendb
    username: userok
    password: password
buttonName:
  shelterInformation: Информация о приюте
  mainMenu: Главное меню
  unknownCommand: Неизвестная команда
  petReport: Прислать отчет о питомце
  adoption: Как взять животное из приюта
  volunteer: Позвать волонтера
  shelterAddress: Адрес