server:
  port: 8091
spring:
  rabbitmq:
    host: 94.158.219.127
    port: 5672
    username: userok
    password: password
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:postgresql://94.158.219.127:5432/toptendb
    username: userok
    password: password
buttonName:
  shelterInformation: Информация о приюте
  mainMenu: Главное меню
  unknownCommand: Неизвестная команда
  petReport: Прислать отчет о питомце
  adoption: Как взять животное из приюта
  volunteer: Позвать волонтера
  shelterAddress: Адрес