server:
  port: 8091
spring:
  rabbitmq:
    host: 94.158.219.127
    port: 5672
    username: userok
    password: password
buttonName:
  shelterInformation: Информация о приюте
  mainMenu: Главное меню
  unknownCommand: Неизвестная команда
  petReport: Прислать отчет о питомце
  adoption: Как взять животное из приюта
  volunteer: Позвать волонтера
  shelterAddress: Адрес
  workScheduleShelter: Расписание работы приюта
  drivingDirections: Схема проезда
  safetyMeasuresInShelter: Техника безопасности на территории приюта
  securityData: Данные охраны для оформления пропуска на машину
  contactForCommunication: Контактные данные для связи


